config/routes.rb
Rails.application.routes.draw do
  get 'uis/index'
  get 'hamburgermenu/index'
  get 'tabmenu/index'
  get 'games/index'
  root "performance#index"
  get 'toppages/index'
  get 'performance/index'
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users, controllers: {
    registrations: 'registrations',
    passwords: 'passwords'
  }
  resources :posts do
    resources :posts, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users#new_guest'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, presence: true
  validates :text, presence: true
  belongs_to :user
  has_many :likes, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: :user_id, dependent: :destroy
  has_many :likes, foreign_key: :user_id, dependent: :destroy
  validates :nickname, presence: true
  validates :nickname, uniqueness: true

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.nickname = "ゲストユーザー"
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def check_guest
    email = resource&.email || params[:user][:email].downcase
    if email == 'guest@example.com'
      redirect_to toppages_index_path, alert: 'ゲストユーザーの変更・削除はできません'
    end
  end

  # deviseアカウント登録後・ログイン後のパスを変更
  def after_sign_in_path_for(resource)
    toppages_index_path
  end

  # deviseアカウント編集後のパスを変更
  def after_update_path_for(resource)
    toppages_index_path
  end

  # deviseログアウト後のパスを変更
  def after_sign_out_path_for(resource)
    toppages_index_path
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/hamburgermenu_controller.rb
class HamburgermenuController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::ApplicationController
  before_action :check_guest, only: :create

end

app/controllers/performance_controller.rb
class PerformanceController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_action, only: [:destroy, :edit, :update]
  before_action :move_to_index, except: [:index, :show]

  def index
    redirect_to toppages_index_path
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
    else
      @post = Post.includes(:user)
      redirect_to toppages_index_path, alert: '新規投稿に失敗しました'
    end
  end

  def destroy
    @post.destroy
  end

  def edit
  end

  def update
    @post.update(post_params)
  end

  private
  def post_params
    params.require(:post).permit(:name, :image, :text).merge(user_id: current_user.id)
  end

  def find_action
    @post = Post.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

end

app/controllers/tabmenu_controller.rb
class TabmenuController < ApplicationController
  def index
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @posts = Post.includes(:user)
    @posts = Post.all.page(params[:page]).per(5)
    # ページネーションが1ページに表示するレコード数はデフォルトで25件です
    # 変更する場合は、.per()の数字を編集して下さい
  end
end

app/controllers/uis_controller.rb
class UisController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to toppages_index_path, notice: 'ゲストユーザーとしてログインしました'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.haml
てんしょくクエストv1.0.0
%br
.game-wrapper
  .game-wrapper__section
    .game-wrapper__section__enemy
      %h2#enemyName
      .hpGauge
        .hpGauge__value#currentEnemyHpGaugeValue
      .hp
        #currentEnemyHp
        #EnemyHp
    .game-wrapper__line
      VS
    .game-wrapper__section__player
      %h2#playerName
      .hpGauge
        .hpGauge__value#currentPlayerHpGaugeValue
      .hp
        #currentPlayerHp
        #PlayerHp
      .playerStatus
        .killedNumbers
          討伐数:
          #nowkilledNumber
          #targetkillsNumber
      %ul#logs.logs
      %button#attack.attack 攻撃する
.gamemask#gamemask
.gamemodal#gamemodal
  %h2.gamemodaltitle#modalTitle
  %a.modalNextButton#modalNextButton To be continued...
  %a.modalCloseButton#modalCloseButton 閉じる

app/views/hamburgermenu/_link.html.haml
.hamburgermenu-header
  %a.menuButton#menuButton
    .div
    .div
    .div
  .hamburger-nav#hamburger-nav
    %ul
      %li
        = link_to "easy chat", toppages_index_path, method: :get
      %li
        = link_to "てんしょくクエスト", games_index_path, method: :get

app/views/hamburgermenu/index.html.haml
%h1 hamburgermenuのindexです！

app/views/layouts/_header.html.haml
.header
  .header__bar
    .header__bar__left
      ようこそ！
      - if user_signed_in?
        .header__bar__left__name
          = link_to "#{current_user.nickname}さん", edit_user_registration_path, method: :get
    .header__bar__right
      %ul.header-item
        %li.toggle-infomation
          %i.fas.fa-exclamation-circle
            .darkmode-tooltiptext
              黒を基調とした背景で閲覧できます
          .darkmode-text
            ダークモード
        %li.toggle-switch
          %input#toggle.toggle-input{type: "checkbox"}/
          %label.toggle-label{for: "toggle"}
        - if user_signed_in?
          %li.header-bar-item
            = link_to "新規投稿", new_post_path, method: :get
          %li.header-bar-item
            = link_to "ログアウト", destroy_user_session_path, method: :delete
        - else
          %li.header-bar-item
            = link_to "ログイン", new_user_session_path, method: :get
          %li.header-bar-item
            = link_to "新規登録", new_user_registration_path, method: :get
          %li.header-bar-item
            = link_to "ゲストログイン（登録不要）", users_guest_sign_in_path, method: :post
        // ダークモード
        :javascript
          // チェックボックスの取得
          const btn = document.querySelector("#toggle");
          // チェックした時の挙動
          btn.addEventListener("change", () => {
            if (btn.checked == true) {
              // ダークモード
              document.body.classList.remove("light-theme");
              document.body.classList.add("dark-theme");
            } else {
              // ライトモード
              document.body.classList.remove("dark-theme");
              document.body.classList.add("light-theme");
            }
          });

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_pagetop.html.haml
/ ページトップボタン
%p.page-top{style: "display: block;"}
  %a{href: "#"}
    %i.fas.fa-chevron-up

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{content: "width=device-width,initial-scale=1.0", name: "viewport"}/
    %title Oa
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield
    = render partial: "layouts/pagetop"
    = javascript_include_tag 'application', defer: 'defer'
    -# defer: 'defer' scriptを非同期ダウンロードし、HTMLパース完了後にscriptを実行する

app/views/likes/_like.html.haml
- if user_signed_in?
  - unless post.like_user(current_user.id).blank?
    = link_to post_like_path(post_id: post.id ,id: post.likes[0].id), method: :delete, remote: true do
      %i.fas.fa-heart
        = post.likes_count
    .like-text
      いいね！
  - else
    = link_to post_likes_path(post.id), method: :post, remote: true do
      %i.fas.fa-heart
        = post.likes_count
    .like-text
      いいね！

app/views/likes/create.js.haml
$('#likes_buttons_#{@post.id}').html("#{j(render partial: 'likes/like', locals: {post: @post})}");

app/views/likes/destroy.js.haml
$('#likes_buttons_#{@post.id}').html("#{j(render partial: 'likes/like', locals: {post: @post})}");

app/views/performance/_container.html.haml
.performance-container
  .performance-container__title
    SKILL BADGES
    %br
      %span
        OF
    COLLECTION
  .badge-icon
    .badge-icon__block
      %i.fas.fa-user-lock
      .badge-text
        .badge-text__index
          %a GUEST USER
    .badge-icon__block
      %i.fas.fa-toggle-on
      .badge-text
        .badge-text__index
          %a TOGGLE SWITCH
    .badge-icon__block
      %i.fas.fa-moon
      .badge-text
        .badge-text__index
          %a DARK MODE
    .badge-icon__block
      %i.fas.fa-exclamation-circle
      .badge-text
        .badge-text__index
          %a HOVER ON
    .badge-icon__block
      %i.fas.fa-heart
      .badge-text
        .badge-text__index
          %a FAVORITE
    .badge-icon__block
      %i.fas.fa-bolt
      .badge-text
        .badge-text__index
          %a PAGENATION
    .badge-icon__block
      %i.fas.fa-bars
      .badge-text
        .badge-text__index
          %a{href: hamburgermenu_index_path} HAMBURGER MENU
    .badge-icon__block
      %i.fas.fa-mobile-alt
      .badge-text
        .badge-text__index
          %a RESPONSIVE
    .badge-icon__block
      %i.fas.fa-arrow-circle-up
      .badge-text
        .badge-text__index
          %a TOP SCROLL
    .badge-icon__block
      %i.far.fa-images
      .badge-text
        .badge-text__index
          %a SLIDE SHOW
  .badge-icon
    .badge-icon__block
      %i.fas.fa-caret-square-down
      .badge-text
        .badge-text__index
          %a ACCORDION MENU
    .badge-icon__block
      %i.far.fa-window-maximize
      .badge-text
        .badge-text__index
          %a#modalOpen MODAL WINDOW
    .badge-icon__block
      %i.fas.fa-project-diagram
      .badge-text
        .badge-text__index
          %a ERD MODELING
    .badge-icon__block
      %i.fas.fa-box
      .badge-text
        .badge-text__index
          %a{href: tabmenu_index_path} TAB MENU
    .badge-icon__block
      %i.fas.fa-question-circle
      .badge-text
        .badge-text__index
          %a ？？？？？？？？？
    .badge-icon__block
      %i.fas.fa-question-circle
      .badge-text
        .badge-text__index
          %a ？？？？？？？？？
    .badge-icon__block
      %i.fas.fa-question-circle
      .badge-text
        .badge-text__index
          %a ？？？？？？？？？
    .badge-icon__block
      %i.fas.fa-question-circle
      .badge-text
        .badge-text__index
          %a ？？？？？？？？？
    .badge-icon__block
      %i.fas.fa-question-circle
      .badge-text
        .badge-text__index
          %a ？？？？？？？？？

app/views/performance/_graphic.html.haml
.performance-image
  .performance-viewer
    %ul
      %li= image_tag ("img-pc.jpg")
      %li= image_tag ("img-business.jpg")
      %li= image_tag ("img-child.jpg")
      %li= image_tag ("img-coffee.jpg")
      %li= image_tag ("img-cheers.jpg")

app/views/performance/_header.html.haml
.performance-header
  .performance-header__title
    performance
  .performance-header__botton
    = render partial: "hamburgermenu/link"

app/views/performance/_modal.html.haml
.modal#modal
  .modal__contents
    .modal__contents__title
      you are choice a icon
    .modal__contents__icon
      %i.far.fa-window-maximize
    .modal__contents__icon-title
      MODAL WINDOW
    .modal__contents__output
      Please click here for
      = link_to "output.", "/"
  %a#modalClose.modalClose
    ×
.mask#mask

:javascript
  (function () {
    const modalOpen = document.getElementById("modalOpen");
    const modalClose = document.getElementById("modalClose");
    const mask = document.getElementById("mask");
    const toggle = [modalOpen, modalClose, mask];

    for (let i = 0, len = toggle.length; i < len; i++) {
      toggle[i].addEventListener("click", function () {
        modal.classList.toggle("active");
        mask.classList.toggle("active");
        },false
      );
    }
  })();

  // 即時関数 関数定義と同時実行し、関数範囲内のスコープを汚さずに新しいスコープを作ること。関数名は不要で、再利用しない一連の処理で使われる。
  // 変数 const(再代入・再定義不可) > let(再代入のみ可) > var(再代入・再定義可)
  // for (let i = 0, len = 変数.length; i < len; i++){} 配列の長さを変数にキャッシュし、配列の長さの取得を省略する。
  // toggle 指定したクラスの有無を識別し、クラスの追加及び削除を行う。

app/views/performance/_performance_container.html.haml
.performance-container
  .performance-container__title
    SKILL BADGES
    %br
      %span
        OF
    COLLECTION
  .badge-icon
    .badge-icon__block
      %i.fas.fa-user-lock
      .badge-text
        .badge-text__index
          %a#modalOpen GUEST USER
    .badge-icon__block
      %i.fas.fa-toggle-on
      .badge-text
        .badge-text__index
          %a#openModal TOGGLE SWITCH
    .badge-icon__block
      %i.fas.fa-moon
      .badge-text
        .badge-text__index
          %a#openModal DARK MODE
    .badge-icon__block
      %i.fas.fa-exclamation-circle
      .badge-text
        .badge-text__index
          %a#openModal HOVER ON
    .badge-icon__block
      %i.fas.fa-heart
      .badge-text
        .badge-text__index
          %a#openModal FAVORITE
    .badge-icon__block
      %i.fas.fa-bolt
      .badge-text
        .badge-text__index
          %a#openModal PAGENATION
    .badge-icon__block
      %i.fas.fa-bars
      .badge-text
        .badge-text__index
          %a#openModal HAMBURGER MENU
    .badge-icon__block
      %i.fas.fa-mobile-alt
      .badge-text
        .badge-text__index
          %a#openModal RESPONSIVE
    .badge-icon__block
      %i.fas.fa-arrow-circle-up
      .badge-text
        .badge-text__index
          %a#openModal TOP SCROLL
    .badge-icon__block
      %i.far.fa-images
      .badge-text
        .badge-text__index
          %a#openModal SLIDE SHOW
  .badge-icon
    .badge-icon__block
      %i.fas.fa-caret-square-down
      .badge-text
        .badge-text__index
          %a#openModal ACCORDION MENU
    .badge-icon__block
      %i.far.fa-window-maximize
      .badge-text
        .badge-text__index
          %a#openModal MODAL WINDOW
    .badge-icon__block
      %i.fas.fa-project-diagram
      .badge-text
        .badge-text__index
          %a#openModal ERD MODELING
    .badge-icon__block
      %i.fas.fa-question-circle
      .badge-text
        .badge-text__index
          %a#openModal ？？？？？？？？？
    .badge-icon__block
      %i.fas.fa-question-circle
      .badge-text
        .badge-text__index
          %a#openModal ？？？？？？？？？
    .badge-icon__block
      %i.fas.fa-question-circle
      .badge-text
        .badge-text__index
          %a#openModal ？？？？？？？？？
    .badge-icon__block
      %i.fas.fa-question-circle
      .badge-text
        .badge-text__index
          %a#openModal ？？？？？？？？？
    .badge-icon__block
      %i.fas.fa-question-circle
      .badge-text
        .badge-text__index
          %a#openModal ？？？？？？？？？
    .badge-icon__block
      %i.fas.fa-question-circle
      .badge-text
        .badge-text__index
          %a#openModal ？？？？？？？？？
.modal#modal
  .modal__contents
    .modal__contents__title
      you are choice a icon
    .modal__contents__icon
      %i.fas.fa-user-lock
    .modal__contents__icon-title
      GUEST USER
    .modal__contents__output
      Please click here for
      = link_to "output.", "/"
  %a#modalClose.modalClose
    ×
.mask#mask

app/views/performance/_performance_graphic.html.haml
.performance-image
  .performance-viewer
    %ul
      %li= image_tag ("img-pc.jpg")
      %li= image_tag ("img-business.jpg")
      %li= image_tag ("img-child.jpg")
      %li= image_tag ("img-coffee.jpg")
      %li= image_tag ("img-cheers.jpg")

app/views/performance/_performance_header.html.haml
.performance-header
  .performance-header__title
    performance
  .performance-header__botton
    %a#panel-btn{href: "#"}
      %span#panel-btn-icon
    #panel
      = link_to "チャットに移動する", toppages_index_path, method: :get

app/views/performance/index.html.haml
.wrapper
  = render partial: "performance/header"
  = render partial: "performance/graphic"
  = render partial: "performance/container"
  = render partial: "performance/modal"

app/views/posts/create.html.haml
= render partial: "layouts/header"

.contents
  .container
    .success
      %h3 投稿が完了しました。
      .success__btn
        %a.btn{href: toppages_index_path} 投稿一覧へ戻る

app/views/posts/destroy.html.haml
= render partial: "layouts/header"

.contents
  .container
    .success
      %h3 削除が完了しました。
      .success__btn
        %a.btn{href: toppages_index_path} 投稿一覧へ戻る

app/views/posts/edit.html.haml
= render partial: "layouts/header"

.contents
  .container
    = form_with(model: @post, local: true) do |form|
      %h3 編集する
      = form.text_field :name, placeholder: "name"
      = form.text_area :text, placeholder: "text", rows: "10", class: 'text-form'
      = form.submit "SEND", class: 'action-botton'

app/views/posts/new.html.haml
= render partial: "layouts/header"

.contents
  .container
    = form_with(model: @post, local: true) do |form|
      %h3 投稿する
      = form.text_field :name, placeholder: "name"
      = form.text_area :text, placeholder: "text", rows: "10", class: 'text-form'
      = form.submit "SEND", class: 'action-botton'

app/views/posts/update.html.haml
= render partial: "layouts/header"

.contents
  .container
    .success
      %h3 編集が完了しました。
      .success__btn
        %a.btn{href: toppages_index_path} 投稿一覧へ戻る

app/views/tabmenu/index.html.haml
.tabmenu-container
  %ul.tabmenu-container__tabs
    %li
      %a.active メニュー1
    %li
      %a メニュー2
    %li
      %a メニュー3
  %ul.tabmenu-container__contents
    %li.active
      メニュー1のコンテンツ
    %li
      メニュー2のコンテンツ
    %li
      メニュー3のコンテンツ

app/views/toppages/_container.html.haml
.main-container
  .message
    .message__top-title
      %i.fas.fa-comment-dots.fa-2x
      メッセージ一覧
    %hr
    - @posts.each do |post|
      .message__name
        = "#{post.name}："
        %time(datetime="#{post.created_at}")= time_ago_in_words(post.created_at)
      .message__text
        = post.text
        .edit-actions
          - if user_signed_in? && post.user_id == current_user.id
            = link_to "編集", edit_post_path(post.id), method: :get, class:"edit-actions-btn"
            = link_to "削除", post_path(post.id), method: :delete, class:"edit-actions-btn", data: {confirm: "投稿を削除します。よろしいですか？"}
      .like-alia
        .like-alia__link{id: "likes_buttons_#{post.id}"}
          = render partial: 'likes/like', locals: { post: post, likes: @likes}
    %hr
    = paginate @posts
  .message-tools
    %ul.debug-tool
      %h4.debug-tool-text
        %i.fas.fa-wrench.fa-2x
        アプリ検証ツール一覧
      %hr
      %h4.debug-tool-text
        %i.fas.fa-sync-alt.fa-2x
        リダイレクト
        %i.fas.fa-exclamation-circle
          .tooltiptext
            未ログイン状態でご確認下さい
      %li.debug-tool-item
        = link_to "新規投稿", new_post_path, method: :get, :onclick => "clickEvent()"
          - unless user_signed_in?
          :javascript
            function clickEvent (){
            alert('ログイン状態ではない為、リダイレクトします。');
            }
      %hr
      %h4.debug-tool-text
        %i.fas.fa-user.fa-2x
        アカウント削除
        %i.fas.fa-exclamation-circle
          .tooltiptext
            ゲストユーザー以外削除します
      %li.debug-tool-item
        - if user_signed_in? && current_user.email == "guest@example.com"
          = link_to "アカウント削除", user_registration_path, method: :delete
        - else
          = link_to "アカウント削除", user_registration_path, method: :delete, data: {confirm: "アカウントを削除すると、投稿及びいいね！も消去されます。"}
      %hr
    .performance
      %h4.debug-tool-text
        %i.fas.fa-trophy.fa-2x
        作業実績
        %i.fas.fa-exclamation-circle
          .tooltiptext
            これまで作業を行った記録です
      %hr
      %li.debug-tool-item
        = link_to "作業実績へ", performance_index_path, method: :get

app/views/toppages/_header.html.haml
.header
  .header__bar
    .header__bar__left
      ようこそ！
    .header__bar__right
      %ul.header-item
      - if user_signed_in?
        %li.header-bar-item
          ログインしています
        %li.header-bar-item
          = link_to "ログアウト"
      - else
        %li.header-bar-item
          = link_to "ログイン"
        %li.header-bar-item
          = link_to "新規登録"

app/views/toppages/index.html.haml
.wrapper
  = render partial: "layouts/header"
  = render partial: "container"

app/views/uis/_accordion-menu.html.haml
%ul.accordion-menu
  %li
    %a(href="") 親メニュー1
    %ul
      %li
        %a(href="")子メニュー1
      %li
        %a(href="")子メニュー2
      %li
        %a(href="")子メニュー3
  %li
    %a(href="") 親メニュー2
    %ul
      %li
        %a(href="")子メニュー1
      %li
        %a(href="")子メニュー2
      %li
        %a(href="")子メニュー3
  %li
    %a(href="") 親メニュー3
    %ul
      %li
        %a(href="")子メニュー1
      %li
        %a(href="")子メニュー2
      %li
        %a(href="")子メニュー3

app/views/uis/_hamburger-menu.html.haml
.hamburgermenu-header
  %a.menuButton#menuButton
    .div
    .div
    .div
  .hamburger-nav#hamburger-nav
    %ul
      %li
        = link_to "リンク先"
      %li
        コンテンツ

app/views/uis/_modal.html.haml
.modal#modal
  .modal__contents
    .modal__contents__title
      you are choice a icon
    .modal__contents__icon
      %i.far.fa-window-maximize
    .modal__contents__icon-title
      モーダルタイトル
    .modal__contents__output
      Please click here for
      = link_to "output.", "/"
  %a#modalClose.modalClose
    ×
.mask#mask

:javascript
  (function () {
    const modalOpen = document.getElementById("modalOpen");
    const modalClose = document.getElementById("modalClose");
    const mask = document.getElementById("mask");
    const toggle = [modalOpen, modalClose, mask];

    for (let i = 0, len = toggle.length; i < len; i++) {
      toggle[i].addEventListener("click", function () {
        modal.classList.toggle("active");
        mask.classList.toggle("active");
        },false
      );
    }
  })();

  // 即時関数 関数定義と同時実行し、関数範囲内のスコープを汚さずに新しいスコープを作ること。関数名は不要で、再利用しない一連の処理で使われる。
  // 変数 const(再代入・再定義不可) > let(再代入のみ可) > var(再代入・再定義可)
  // for (let i = 0, len = 変数.length; i < len; i++){} 配列の長さを変数にキャッシュし、配列の長さの取得を省略する。
  // toggle 指定したクラスの有無を識別し、クラスの追加及び削除を行う。

app/views/uis/_tabmenu.html.haml
.tabmenu-container
  %ul.tabmenu-container__tabs
    %li
      %a.active メニュー1
    %li
      %a メニュー2
    %li
      %a メニュー3
  %ul.tabmenu-container__contents
    %li.active
      メニュー1のコンテンツ
    %li
      メニュー2のコンテンツ
    %li
      メニュー3のコンテンツ

app/views/uis/_toggle-switch.html.haml
.toggle-switch
  %input#toggle.toggle-input{type: "checkbox"}/
  %label.toggle-label{for: "toggle"}

app/views/uis/index.html.haml
%h1 Uis#index
%p Find me in app/views/uis/index.html.haml

%a#modalOpen MODAL WINDOW

= render partial: "uis/hamburger-menu"

= render partial: "uis/tabmenu"

= render partial: "uis/toggle-switch"

= render partial: "uis/modal"

= render partial: "uis/accordion-menu"